services:
  fetch.receiptprocessor:
    image: fetch.receiptprocessor
    build:
      context: .
      dockerfile: Fetch.ReceiptProcessor/Dockerfile
    ports:
      - "18080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

#docker-compose build --no-cache
#docker-compose up -d
#docker-compose down

